BINARY_NAME=myfs.exe
SRC_DIR=src
BUILD_DIR=..\bin

all: build

build:
	if not exist $(BUILD_DIR) mkdir $(BUILD_DIR)
	cd $(SRC_DIR) && go build -o ..\bin\$(BINARY_NAME) main.go && cd ..

clean:
	if exist $(BUILD_DIR) rmdir /s /q $(BUILD_DIR)

.PHONY: all build clean
